# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ba4ab5aa0e553d072ab86de5f060e44e381aa88ed28c79200119ce130d4139d963e87fb454946a3c9c47b54c6f1e9eefb07c4ada7980bc4cf90b55ad6c0387

test:
  secret_key_base: 8683aff2eda2045b4816aa28d4197b02ae4ecf522eab1660466101760e81da49084c20d4973521895188efdddd6dd491ebad2fb4407ff98f394af04196ae4c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
